"""MkDocs hook: keep the pre-2026 flat URLs working.

Every page used to live at the site root. map.json (generated by
tools/restructure/restructure.py) lists each old page with the new URL of every
heading that moved to a different page or id; "" is where the page itself went.
Each old URL gets a small stub that picks the target from the fragment, so a
pasted link like /graphicsprocessingunitgpu/#gpu-timings lands on the right
section of the right page. Anchors the map does not list are passed through.
"""
import html
import json
import os

MAP = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'map.json')

STUB = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Moved</title>
<link rel="canonical" href="{canonical}">
<script>
var m = {table};
var h = location.hash.slice(1);
try {{ h = decodeURIComponent(h); }} catch (e) {{}}
var t = Object.prototype.hasOwnProperty.call(m, h) ? m[h] : m[""] + (h ? "#" + h : "");
location.replace("../" + t);
</script>
<noscript><meta http-equiv="refresh" content="0; url=../{default}"></noscript>
</head>
<body><p>This page has moved to <a href="../{default}">{default}</a>.</p></body>
</html>
"""


def on_post_build(config):
    site = config['site_dir']
    base = (config.get('site_url') or '').rstrip('/') + '/'
    with open(MAP, encoding='utf-8') as f:
        pages = json.load(f)
    for old, table in pages.items():
        out = os.path.join(site, old, 'index.html')
        if os.path.exists(out):
            raise RuntimeError(f'redirect for /{old}/ would overwrite a real page')
        os.makedirs(os.path.dirname(out), exist_ok=True)
        default = html.escape(table[''])
        with open(out, 'w', encoding='utf-8') as f:
            f.write(STUB.format(table=json.dumps(table, sort_keys=True).replace('</', '<\\/'),
                                default=default, canonical=base + default))
